# Generated by Django 4.2.3 on 2023-07-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
